[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"
  framework = "#static"

[functions]
  directory = "netlify/functions"
  
[[plugins]]
package = "@netlify/plugin-functions-install-core"
